package protocolsupport.protocol.typeremapper.entity.format.metadata.types.base;

import protocolsupport.protocol.typeremapper.entity.format.metadata.object.value.NetworkEntityMetadataObjectIndexValueNoOpTransformer;
import protocolsupport.protocol.types.networkentity.metadata.NetworkEntityMetadataObjectIndexRegistry;
import protocolsupport.protocol.utils.ProtocolVersionsHelper;

public class AbstractMerchantNetworkEntityMetadataFormatTransformerFactory<R extends NetworkEntityMetadataObjectIndexRegistry.AbstractMerchantIndexRegistry> extends AgeableNetworkEntityMetadataFormatTransformerFactory<R> {

	public static final AbstractMerchantNetworkEntityMetadataFormatTransformerFactory<NetworkEntityMetadataObjectIndexRegistry.AbstractMerchantIndexRegistry> INSTANCE = new AbstractMerchantNetworkEntityMetadataFormatTransformerFactory<>(NetworkEntityMetadataObjectIndexRegistry.AbstractMerchantIndexRegistry.INSTANCE);

	protected AbstractMerchantNetworkEntityMetadataFormatTransformerFactory(R registry) {
		super(registry);

		add(new NetworkEntityMetadataObjectIndexValueNoOpTransformer(registry.HEAD_SHAKE_TIMER, 17), ProtocolVersionsHelper.UP_1_17);
		add(new NetworkEntityMetadataObjectIndexValueNoOpTransformer(registry.HEAD_SHAKE_TIMER, 16), ProtocolVersionsHelper.RANGE__1_15__1_16_4);
		add(new NetworkEntityMetadataObjectIndexValueNoOpTransformer(registry.HEAD_SHAKE_TIMER, 15), ProtocolVersionsHelper.RANGE__1_14_1__1_14_4);
	}

}
