package protocolsupport.protocol.types.command;

import protocolsupport.protocol.utils.EnumConstantLookup;

public enum CommandNodeArgumentType {
	BOOLEAN, FLOAT, DOUBLE, INTEGER, LONG, STRING, ENTITY, GAMEPROFILE, BLOCK_POSITION, COLUMN_POSITION, VEC3D, VEC2D, BLOCKSTATE, BLOCK_PREDICATE, ITEMSTACK, ITEM_PREDICATE, CHAT_COLOR,
	CHAT_COMPONENT, CHAT_MESSAGE, NBT, NBT_TAG, NBT_PATH, OBJECTIVE, OBJECTIVE_CRITERIA, OPERATION, PARTICLE, ANGLE, ROTATION, SCOREBOARD_SLOT, SCORE_HOLDER, SWIZZLE, TEAM, SLOT, RESOURCE_LOCATION,
	FUNCTION, ENTITY_ANCHOR, RANGE_INT, RANGE_FLOAT, DIMENSION, GAMEMODE, TIME, RESOURCE_OR_TAG, RESOURCE_OR_TAG_KEY, RESOURCE, RESOURCE_KEY, TEMPLATE_MIRROR, TEMPLATE_ROTATION, HEIGHTMAP, UUID;

	public static final EnumConstantLookup<CommandNodeArgumentType> CONSTANT_LOOKUP = new EnumConstantLookup<>(CommandNodeArgumentType.class);
}