package protocolsupport.protocol.pipeline.version.v_1_14.r1;

import protocolsupport.api.utils.NetworkState;
import protocolsupport.protocol.packet.middle.impl.serverbound.IServerboundMiddlePacketV14r1;
import protocolsupport.protocol.packet.middle.impl.serverbound.handshake.v_7__20.SetProtocol;
import protocolsupport.protocol.packet.middle.impl.serverbound.login.v_13__20.LoginCustomPayload;
import protocolsupport.protocol.packet.middle.impl.serverbound.login.v_7__18.LoginStart;
import protocolsupport.protocol.packet.middle.impl.serverbound.login.v_8__20.EncryptionResponse;
import protocolsupport.protocol.packet.middle.impl.serverbound.play.v_10__20.ResourcePackStatus;
import protocolsupport.protocol.packet.middle.impl.serverbound.play.v_12r1__20.AdvancementTab;
import protocolsupport.protocol.packet.middle.impl.serverbound.play.v_13__17r1.EditBook;
import protocolsupport.protocol.packet.middle.impl.serverbound.play.v_13__18.SetBeaconEffect;
import protocolsupport.protocol.packet.middle.impl.serverbound.play.v_13__20.CraftRecipeRequest;
import protocolsupport.protocol.packet.middle.impl.serverbound.play.v_13__20.CustomPayload;
import protocolsupport.protocol.packet.middle.impl.serverbound.play.v_13__20.NameItem;
import protocolsupport.protocol.packet.middle.impl.serverbound.play.v_13__20.PickItem;
import protocolsupport.protocol.packet.middle.impl.serverbound.play.v_13__20.QueryEntityNBT;
import protocolsupport.protocol.packet.middle.impl.serverbound.play.v_13__20.SelectTrade;
import protocolsupport.protocol.packet.middle.impl.serverbound.play.v_13__20.TabComplete;
import protocolsupport.protocol.packet.middle.impl.serverbound.play.v_13__20.UpdateCommandMinecart;
import protocolsupport.protocol.packet.middle.impl.serverbound.play.v_14r1__16r1.RecipeBookData;
import protocolsupport.protocol.packet.middle.impl.serverbound.play.v_14r1__18.BlockDig;
import protocolsupport.protocol.packet.middle.impl.serverbound.play.v_14r1__18.BlockPlace;
import protocolsupport.protocol.packet.middle.impl.serverbound.play.v_14r1__20.DifficultyChange;
import protocolsupport.protocol.packet.middle.impl.serverbound.play.v_14r1__20.DifficultyLock;
import protocolsupport.protocol.packet.middle.impl.serverbound.play.v_14r1__20.QueryBlockNBT;
import protocolsupport.protocol.packet.middle.impl.serverbound.play.v_14r1__20.UpdateCommandBlock;
import protocolsupport.protocol.packet.middle.impl.serverbound.play.v_14r1__20.UpdateSign;
import protocolsupport.protocol.packet.middle.impl.serverbound.play.v_14r1__20.UpdateStructureBlock;
import protocolsupport.protocol.packet.middle.impl.serverbound.play.v_4__16r2.InventoryClick;
import protocolsupport.protocol.packet.middle.impl.serverbound.play.v_4__16r2.InventoryClose;
import protocolsupport.protocol.packet.middle.impl.serverbound.play.v_4__16r2.InventoryConfirmTransaction;
import protocolsupport.protocol.packet.middle.impl.serverbound.play.v_4__20.CreativeSetSlot;
import protocolsupport.protocol.packet.middle.impl.serverbound.play.v_4__20.Ground;
import protocolsupport.protocol.packet.middle.impl.serverbound.play.v_4__20.HeldSlot;
import protocolsupport.protocol.packet.middle.impl.serverbound.play.v_4__20.InventoryButton;
import protocolsupport.protocol.packet.middle.impl.serverbound.play.v_4__20.Look;
import protocolsupport.protocol.packet.middle.impl.serverbound.play.v_6__15.PlayerAbilities;
import protocolsupport.protocol.packet.middle.impl.serverbound.play.v_7__20.Chat;
import protocolsupport.protocol.packet.middle.impl.serverbound.play.v_7__20.ClientCommand;
import protocolsupport.protocol.packet.middle.impl.serverbound.play.v_8__20.EntityAction;
import protocolsupport.protocol.packet.middle.impl.serverbound.play.v_8__20.KeepAlive;
import protocolsupport.protocol.packet.middle.impl.serverbound.play.v_8__20.Move;
import protocolsupport.protocol.packet.middle.impl.serverbound.play.v_8__20.Spectate;
import protocolsupport.protocol.packet.middle.impl.serverbound.play.v_8__20.SteerVehicle;
import protocolsupport.protocol.packet.middle.impl.serverbound.play.v_9r1__15.UseEntity;
import protocolsupport.protocol.packet.middle.impl.serverbound.play.v_9r1__16r2.ClientSettings;
import protocolsupport.protocol.packet.middle.impl.serverbound.play.v_9r1__18.UseItem;
import protocolsupport.protocol.packet.middle.impl.serverbound.play.v_9r1__20.Animation;
import protocolsupport.protocol.packet.middle.impl.serverbound.play.v_9r1__20.MoveLook;
import protocolsupport.protocol.packet.middle.impl.serverbound.play.v_9r1__20.MoveVehicle;
import protocolsupport.protocol.packet.middle.impl.serverbound.play.v_9r1__20.SteerBoat;
import protocolsupport.protocol.packet.middle.impl.serverbound.play.v_9r1__20.TeleportAccept;
import protocolsupport.protocol.packet.middle.impl.serverbound.status.v_7__20.Ping;
import protocolsupport.protocol.packet.middle.impl.serverbound.status.v_7__20.ServerInfoRequest;
import protocolsupport.protocol.pipeline.IPacketDataChannelIO;
import protocolsupport.protocol.pipeline.version.util.decoder.AbstractModernPacketDecoder;
import protocolsupport.protocol.storage.netcache.NetworkDataCache;

public class PacketDecoder extends AbstractModernPacketDecoder<IServerboundMiddlePacketV14r1> {

	public PacketDecoder(IPacketDataChannelIO io, NetworkDataCache cache) {
		super(io, cache);
		registry.register(NetworkState.HANDSHAKING, 0x00, SetProtocol::new);
		registry.register(NetworkState.LOGIN, 0x00, LoginStart::new);
		registry.register(NetworkState.LOGIN, 0x01, EncryptionResponse::new);
		registry.register(NetworkState.LOGIN, 0x02, LoginCustomPayload::new);
		registry.register(NetworkState.STATUS, 0x00, ServerInfoRequest::new);
		registry.register(NetworkState.STATUS, 0x01, Ping::new);
		registry.register(NetworkState.PLAY, 0x00, TeleportAccept::new);
		registry.register(NetworkState.PLAY, 0x01, QueryBlockNBT::new);
		registry.register(NetworkState.PLAY, 0x02, DifficultyChange::new);
		registry.register(NetworkState.PLAY, 0x03, Chat::new);
		registry.register(NetworkState.PLAY, 0x04, ClientCommand::new);
		registry.register(NetworkState.PLAY, 0x05, ClientSettings::new);
		registry.register(NetworkState.PLAY, 0x06, TabComplete::new);
		registry.register(NetworkState.PLAY, 0x07, InventoryConfirmTransaction::new);
		registry.register(NetworkState.PLAY, 0x08, InventoryButton::new);
		registry.register(NetworkState.PLAY, 0x09, InventoryClick::new);
		registry.register(NetworkState.PLAY, 0x0A, InventoryClose::new);
		registry.register(NetworkState.PLAY, 0x0B, CustomPayload::new);
		registry.register(NetworkState.PLAY, 0x0C, EditBook::new);
		registry.register(NetworkState.PLAY, 0x0D, QueryEntityNBT::new);
		registry.register(NetworkState.PLAY, 0x0E, UseEntity::new);
		registry.register(NetworkState.PLAY, 0x0F, KeepAlive::new);
		registry.register(NetworkState.PLAY, 0x10, DifficultyLock::new);
		registry.register(NetworkState.PLAY, 0x11, Move::new);
		registry.register(NetworkState.PLAY, 0x12, MoveLook::new);
		registry.register(NetworkState.PLAY, 0x13, Look::new);
		registry.register(NetworkState.PLAY, 0x14, Ground::new);
		registry.register(NetworkState.PLAY, 0x15, MoveVehicle::new);
		registry.register(NetworkState.PLAY, 0x16, SteerBoat::new);
		registry.register(NetworkState.PLAY, 0x17, PickItem::new);
		registry.register(NetworkState.PLAY, 0x18, CraftRecipeRequest::new);
		registry.register(NetworkState.PLAY, 0x19, PlayerAbilities::new);
		registry.register(NetworkState.PLAY, 0x1A, BlockDig::new);
		registry.register(NetworkState.PLAY, 0x1B, EntityAction::new);
		registry.register(NetworkState.PLAY, 0x1C, SteerVehicle::new);
		registry.register(NetworkState.PLAY, 0x1D, RecipeBookData::new);
		registry.register(NetworkState.PLAY, 0x1E, NameItem::new);
		registry.register(NetworkState.PLAY, 0x1F, ResourcePackStatus::new);
		registry.register(NetworkState.PLAY, 0x20, AdvancementTab::new);
		registry.register(NetworkState.PLAY, 0x21, SelectTrade::new);
		registry.register(NetworkState.PLAY, 0x22, SetBeaconEffect::new);
		registry.register(NetworkState.PLAY, 0x23, HeldSlot::new);
		registry.register(NetworkState.PLAY, 0x24, UpdateCommandBlock::new);
		registry.register(NetworkState.PLAY, 0x25, UpdateCommandMinecart::new);
		registry.register(NetworkState.PLAY, 0x26, CreativeSetSlot::new);
		registry.register(NetworkState.PLAY, 0x28, UpdateStructureBlock::new);
		registry.register(NetworkState.PLAY, 0x29, UpdateSign::new);
		registry.register(NetworkState.PLAY, 0x2A, Animation::new);
		registry.register(NetworkState.PLAY, 0x2B, Spectate::new);
		registry.register(NetworkState.PLAY, 0x2C, BlockPlace::new);
		registry.register(NetworkState.PLAY, 0x2D, UseItem::new);
	}

}
