package protocolsupport.protocol.typeremapper.entity.format.metadata.types.living.ageable;

import protocolsupport.protocol.typeremapper.entity.format.metadata.object.value.NetworkEntityMetadataObjectIndexValueNoOpTransformer;
import protocolsupport.protocol.typeremapper.entity.format.metadata.types.base.AgeableNetworkEntityMetadataFormatTransformerFactory;
import protocolsupport.protocol.types.networkentity.metadata.NetworkEntityMetadataObjectIndexRegistry;
import protocolsupport.protocol.utils.ProtocolVersionsHelper;

public class HoglinNetworkEntityMetadataFormatTransformerFactory<R extends NetworkEntityMetadataObjectIndexRegistry.HoglinIndexRegistry> extends AgeableNetworkEntityMetadataFormatTransformerFactory<R> {

	public static final HoglinNetworkEntityMetadataFormatTransformerFactory<NetworkEntityMetadataObjectIndexRegistry.HoglinIndexRegistry> INSTANCE = new HoglinNetworkEntityMetadataFormatTransformerFactory<>(NetworkEntityMetadataObjectIndexRegistry.HoglinIndexRegistry.INSTANCE);

	protected HoglinNetworkEntityMetadataFormatTransformerFactory(R registry) {
		super(registry);

		add(new NetworkEntityMetadataObjectIndexValueNoOpTransformer(registry.ZOMBIFICATION_IMMUNITY, 17), ProtocolVersionsHelper.UP_1_17);
		add(new NetworkEntityMetadataObjectIndexValueNoOpTransformer(registry.ZOMBIFICATION_IMMUNITY, 16), ProtocolVersionsHelper.ALL_1_16);
	}

}
