name: ProtocolSupport
main: protocolsupport.ProtocolSupport
version: ${version}
api-version: 1.19
load: STARTUP

commands:
  protocolsupport:
    description: All ProtocolSupport commands
    aliases: ps
    usage: '/<command> help'

website: 'https://github.com/ProtocolSupport/ProtocolSupport'
authors:
- _Shevchik_
- 7kasper
- MrPowerGamerBR
- gdude2002
