package protocolsupport.protocol.typeremapper.pe;

public class PEPacketIDs {

	public static final int LOGIN = 1;
	public static final int PLAY_STATUS = 2;
	public static final int DISCONNECT = 5;
	public static final int RESOURCE_PACK = 6;
	public static final int RESOURCE_STACK = 7;
	public static final int RESOURCE_RESPONSE = 8;
	public static final int CHAT = 9;
	public static final int UPDATE_TIME = 10;
	public static final int START_GAME = 11;
	public static final int SPAWN_PLAYER = 12;
	public static final int SPAWN_ENTITY = 13;
	public static final int ENTITY_DESTROY = 14;
	public static final int ADD_ITEM_ENTITY = 15;
	//public static final int ADD_HANING_ENTITY = 16; //Simulated
	public static final int TAKE_ITEM_ENTITY = 17;
	public static final int ENTITY_TELEPORT = 18;
	public static final int PLAYER_MOVE = 19;
	public static final int RIDER_JUMP = 20;
	public static final int UPDATE_BLOCK = 21;
	public static final int SPAWN_PAINTING = 22;
	public static final int EXPLODE = 23;
	public static final int LEVEL_SOUND_EVENT = 24;
	public static final int LEVEL_EVENT = 25;
	public static final int TILE_EVENT = 26;
	public static final int ENTITY_EVENT = 27;
	public static final int ENTITY_EFFECT = 28;
	public static final int SET_ATTRIBUTES = 29;
	public static final int GOD_PACKET = 30;
	public static final int MOB_EQUIPMENT = 31;
	public static final int MOB_ARMOR_EQUIPMENT = 32;
	public static final int INTERACT = 33;
	public static final int BLOCK_PICK_REQUEST = 34;
	public static final int ENTITY_PICK_REQUEST = 35;
	public static final int PLAYER_ACTION = 36;
	//public static final int ENTITY_FALL = 37; //Simulated
	//public static final int HURT_ARMOR = 38; //Simulated
	public static final int SET_ENTITY_DATA = 39;
	public static final int ENTITY_VELOCITY = 40;
	public static final int ENTITY_LINK = 41;
	//public static final int SET_HEALTH = 42; //Simulated
	public static final int SPAWN_POS = 43;
	public static final int ANIMATION = 44;
	public static final int RESPAWN_POS = 45;
	public static final int CONTAINER_OPEN = 46;
	public static final int CONTAINER_CLOSE = 47;
	public static final int PLAYER_HOTBAR = 48;
	public static final int INVENTORY_CONTENT = 49;
	public static final int INVENTORY_SLOT = 50;
	public static final int CONTAINER_DATA = 51;
	public static final int CRAFTING_DATA = 52;
	//public static final int CRAFTING_EVENT = 53;
	//public static final int GUI_DATA_PICK_ITEM = 54;
	public static final int ADVENTURE_SETTINGS = 55;
	public static final int TILE_DATA_UPDATE = 56;
	public static final int PLAYER_STEER = 57;
	public static final int CHUNK_DATA = 58;
	//public static final int SET_COMMANDS_ENABLED = 59;
	public static final int SET_DIFFICULTY = 60;
	public static final int CHANGE_DIMENSION = 61;
	public static final int CHANGE_PLAYER_GAMETYPE = 62;
	public static final int PLAYER_INFO = 63;
	//public static final int SIMPLE_EVENT = 64;
	//public static final int TELEMETRY_EVENT = 65;
	//public static final int SPAWN_XP_ORB = 66; //Simulated
	public static final int MAP_ITEM_DATA = 67;
	public static final int MAP_INFO_REQUEST = 68;
	public static final int CLIENT_SETTINGS = 69;
	public static final int CHUNK_RADIUS = 70;
	public static final int ITEM_FRAME_DROP = 71;
	public static final int GAME_RULE_CHANGE = 72;
	//public static final int BOSS_EVENT = 74;
	//public static final int SHOW_CREDITS = 75;
	//public static final int TAB_COMPLETE = 76;
	public static final int COMMAND_REQUEST = 77;
	//public static final int COMMAND_BLOCK_UPDATE = 78;
	public static final int TRADE_UPDATE = 80;
	public static final int EQUIPMENT = 81;
	public static final int RESOURCE_INFO = 82;
	public static final int RESOURCE_DATA = 83;
	public static final int RESOURCE_REQUEST = 84;
	public static final int TRANSFER = 85;
	public static final int PLAY_SOUND = 86;
	public static final int STOP_SOUND = 87;
	public static final int SET_TITLE = 88;
	public static final int PLAYER_SKIN = 93;
	//public static final int SUB_LOGIN = 94;
	//public static final int LAST_HURT = 96;
	public static final int EDIT_BOOK = 97;
	//public static final int NPC_REQUEST = 98;
	//public static final int PHOTO_TRANSFER = 99;
	public static final int MODAL_REQUEST = 100;
	public static final int MODAL_RESPONSE = 101;
	//public static final int SETTINGS_REQUEST = 102;
	//public static final int SETTINGS_RESPONSE = 103;
	//public static final int SHOW_PROFILE = 104;
	//public static final int SET_DEFAULT_GAMEMODE = 105;

}
