package protocolsupport.protocol.typeremapper.entity.format.metadata.types.living.skeleton;

import protocolsupport.api.ProtocolVersion;
import protocolsupport.protocol.typeremapper.entity.format.metadata.object.value.NetworkEntityMetadataInsentientFlagsToLegacySwingingHandsTransformer;
import protocolsupport.protocol.typeremapper.entity.format.metadata.types.base.InsentientNetworkEntityMetadataFormatTransformerFactory;
import protocolsupport.protocol.types.networkentity.metadata.NetworkEntityMetadataObjectIndexRegistry;
import protocolsupport.protocol.utils.ProtocolVersionsHelper;

public class LegacySkeletonNetworkEntityMetadataFormatTransformerFactory<R extends NetworkEntityMetadataObjectIndexRegistry.InsentientIndexRegistry> extends InsentientNetworkEntityMetadataFormatTransformerFactory<R> {

	public static final LegacySkeletonNetworkEntityMetadataFormatTransformerFactory<NetworkEntityMetadataObjectIndexRegistry.InsentientIndexRegistry> INSTANCE = new LegacySkeletonNetworkEntityMetadataFormatTransformerFactory<>(NetworkEntityMetadataObjectIndexRegistry.InsentientIndexRegistry.INSTANCE);

	protected LegacySkeletonNetworkEntityMetadataFormatTransformerFactory(R registry) {
		super(registry);

		add(new NetworkEntityMetadataInsentientFlagsToLegacySwingingHandsTransformer(registry.INS_FLAGS, 12), ProtocolVersionsHelper.RANGE__1_11__1_13_2);
		add(new NetworkEntityMetadataInsentientFlagsToLegacySwingingHandsTransformer(registry.INS_FLAGS, 13), ProtocolVersion.MINECRAFT_1_10);
		add(new NetworkEntityMetadataInsentientFlagsToLegacySwingingHandsTransformer(registry.INS_FLAGS, 12), ProtocolVersionsHelper.ALL_1_9);
	}

}
