package protocolsupport.protocol.pipeline.version.v_1_20;

import protocolsupport.api.utils.NetworkState;
import protocolsupport.protocol.packet.middle.impl.serverbound.IServerboundMiddlePacketV20;
import protocolsupport.protocol.packet.middle.impl.serverbound.handshake.v_7__20.SetProtocol;
import protocolsupport.protocol.packet.middle.impl.serverbound.login.v_13__20.LoginCustomPayload;
import protocolsupport.protocol.packet.middle.impl.serverbound.login.v_19__20.LoginStart;
import protocolsupport.protocol.packet.middle.impl.serverbound.login.v_8__20.EncryptionResponse;
import protocolsupport.protocol.packet.middle.impl.serverbound.play.v_10__20.ResourcePackStatus;
import protocolsupport.protocol.packet.middle.impl.serverbound.play.v_12r1__20.AdvancementTab;
import protocolsupport.protocol.packet.middle.impl.serverbound.play.v_13__20.CraftRecipeRequest;
import protocolsupport.protocol.packet.middle.impl.serverbound.play.v_13__20.CustomPayload;
import protocolsupport.protocol.packet.middle.impl.serverbound.play.v_13__20.NameItem;
import protocolsupport.protocol.packet.middle.impl.serverbound.play.v_13__20.PickItem;
import protocolsupport.protocol.packet.middle.impl.serverbound.play.v_13__20.QueryEntityNBT;
import protocolsupport.protocol.packet.middle.impl.serverbound.play.v_13__20.SelectTrade;
import protocolsupport.protocol.packet.middle.impl.serverbound.play.v_13__20.TabComplete;
import protocolsupport.protocol.packet.middle.impl.serverbound.play.v_13__20.UpdateCommandMinecart;
import protocolsupport.protocol.packet.middle.impl.serverbound.play.v_14r1__20.DifficultyChange;
import protocolsupport.protocol.packet.middle.impl.serverbound.play.v_14r1__20.DifficultyLock;
import protocolsupport.protocol.packet.middle.impl.serverbound.play.v_14r1__20.QueryBlockNBT;
import protocolsupport.protocol.packet.middle.impl.serverbound.play.v_14r1__20.UpdateCommandBlock;
import protocolsupport.protocol.packet.middle.impl.serverbound.play.v_14r1__20.UpdateSign;
import protocolsupport.protocol.packet.middle.impl.serverbound.play.v_14r1__20.UpdateStructureBlock;
import protocolsupport.protocol.packet.middle.impl.serverbound.play.v_16r1__20.JigsawGenerate;
import protocolsupport.protocol.packet.middle.impl.serverbound.play.v_16r1__20.JigsawUpdate;
import protocolsupport.protocol.packet.middle.impl.serverbound.play.v_16r1__20.PlayerAbilities;
import protocolsupport.protocol.packet.middle.impl.serverbound.play.v_16r1__20.UseEntity;
import protocolsupport.protocol.packet.middle.impl.serverbound.play.v_16r2__20.RecipeBookRecipe;
import protocolsupport.protocol.packet.middle.impl.serverbound.play.v_16r2__20.RecipeBookState;
import protocolsupport.protocol.packet.middle.impl.serverbound.play.v_17r1__20.InventoryClose;
import protocolsupport.protocol.packet.middle.impl.serverbound.play.v_17r1__20.SyncPong;
import protocolsupport.protocol.packet.middle.impl.serverbound.play.v_17r2__18.EditBook;
import protocolsupport.protocol.packet.middle.impl.serverbound.play.v_17r2__18.InventoryClick;
import protocolsupport.protocol.packet.middle.impl.serverbound.play.v_18.ClientSettings;
import protocolsupport.protocol.packet.middle.impl.serverbound.play.v_20.BlockDig;
import protocolsupport.protocol.packet.middle.impl.serverbound.play.v_20.BlockPlace;
import protocolsupport.protocol.packet.middle.impl.serverbound.play.v_20.ChatCommand;
import protocolsupport.protocol.packet.middle.impl.serverbound.play.v_20.ChatMessage;
import protocolsupport.protocol.packet.middle.impl.serverbound.play.v_20.ChatMessageAck;
import protocolsupport.protocol.packet.middle.impl.serverbound.play.v_20.ChatSessionUpdate;
import protocolsupport.protocol.packet.middle.impl.serverbound.play.v_20.SetBeaconEffect;
import protocolsupport.protocol.packet.middle.impl.serverbound.play.v_20.UseItem;
import protocolsupport.protocol.packet.middle.impl.serverbound.play.v_4__20.CreativeSetSlot;
import protocolsupport.protocol.packet.middle.impl.serverbound.play.v_4__20.Ground;
import protocolsupport.protocol.packet.middle.impl.serverbound.play.v_4__20.HeldSlot;
import protocolsupport.protocol.packet.middle.impl.serverbound.play.v_4__20.InventoryButton;
import protocolsupport.protocol.packet.middle.impl.serverbound.play.v_4__20.Look;
import protocolsupport.protocol.packet.middle.impl.serverbound.play.v_7__20.ClientCommand;
import protocolsupport.protocol.packet.middle.impl.serverbound.play.v_8__20.EntityAction;
import protocolsupport.protocol.packet.middle.impl.serverbound.play.v_8__20.KeepAlive;
import protocolsupport.protocol.packet.middle.impl.serverbound.play.v_8__20.Move;
import protocolsupport.protocol.packet.middle.impl.serverbound.play.v_8__20.Spectate;
import protocolsupport.protocol.packet.middle.impl.serverbound.play.v_8__20.SteerVehicle;
import protocolsupport.protocol.packet.middle.impl.serverbound.play.v_9r1__20.Animation;
import protocolsupport.protocol.packet.middle.impl.serverbound.play.v_9r1__20.MoveLook;
import protocolsupport.protocol.packet.middle.impl.serverbound.play.v_9r1__20.MoveVehicle;
import protocolsupport.protocol.packet.middle.impl.serverbound.play.v_9r1__20.SteerBoat;
import protocolsupport.protocol.packet.middle.impl.serverbound.play.v_9r1__20.TeleportAccept;
import protocolsupport.protocol.packet.middle.impl.serverbound.status.v_7__20.Ping;
import protocolsupport.protocol.packet.middle.impl.serverbound.status.v_7__20.ServerInfoRequest;
import protocolsupport.protocol.pipeline.IPacketDataChannelIO;
import protocolsupport.protocol.pipeline.version.util.decoder.AbstractModernPacketDecoder;
import protocolsupport.protocol.storage.netcache.NetworkDataCache;

public class PacketDecoder extends AbstractModernPacketDecoder<IServerboundMiddlePacketV20> {

	public PacketDecoder(IPacketDataChannelIO io, NetworkDataCache cache) {
		super(io, cache);
		registry.register(NetworkState.HANDSHAKING, 0x00, SetProtocol::new);
		registry.register(NetworkState.LOGIN, 0x00, LoginStart::new);
		registry.register(NetworkState.LOGIN, 0x01, EncryptionResponse::new);
		registry.register(NetworkState.LOGIN, 0x02, LoginCustomPayload::new);
		registry.register(NetworkState.STATUS, 0x00, ServerInfoRequest::new);
		registry.register(NetworkState.STATUS, 0x01, Ping::new);
		registry.register(NetworkState.PLAY, 0x00, TeleportAccept::new);
		registry.register(NetworkState.PLAY, 0x01, QueryBlockNBT::new);
		registry.register(NetworkState.PLAY, 0x02, DifficultyChange::new);
		registry.register(NetworkState.PLAY, 0x03, ChatMessageAck::new);
		registry.register(NetworkState.PLAY, 0x04, ChatCommand::new);
		registry.register(NetworkState.PLAY, 0x05, ChatMessage::new);
		registry.register(NetworkState.PLAY, 0x06, ChatSessionUpdate::new);
		registry.register(NetworkState.PLAY, 0x07, ClientCommand::new);
		registry.register(NetworkState.PLAY, 0x08, ClientSettings::new);
		registry.register(NetworkState.PLAY, 0x09, TabComplete::new);
		registry.register(NetworkState.PLAY, 0x0A, InventoryButton::new);
		registry.register(NetworkState.PLAY, 0x0B, InventoryClick::new);
		registry.register(NetworkState.PLAY, 0x0C, InventoryClose::new);
		registry.register(NetworkState.PLAY, 0x0D, CustomPayload::new);
		registry.register(NetworkState.PLAY, 0x0E, EditBook::new);
		registry.register(NetworkState.PLAY, 0x0F, QueryEntityNBT::new);
		registry.register(NetworkState.PLAY, 0x10, UseEntity::new);
		registry.register(NetworkState.PLAY, 0x11, JigsawGenerate::new);
		registry.register(NetworkState.PLAY, 0x12, KeepAlive::new);
		registry.register(NetworkState.PLAY, 0x13, DifficultyLock::new);
		registry.register(NetworkState.PLAY, 0x14, Move::new);
		registry.register(NetworkState.PLAY, 0x15, MoveLook::new);
		registry.register(NetworkState.PLAY, 0x16, Look::new);
		registry.register(NetworkState.PLAY, 0x17, Ground::new);
		registry.register(NetworkState.PLAY, 0x18, MoveVehicle::new);
		registry.register(NetworkState.PLAY, 0x19, SteerBoat::new);
		registry.register(NetworkState.PLAY, 0x1A, PickItem::new);
		registry.register(NetworkState.PLAY, 0x1B, CraftRecipeRequest::new);
		registry.register(NetworkState.PLAY, 0x1C, PlayerAbilities::new);
		registry.register(NetworkState.PLAY, 0x1D, BlockDig::new);
		registry.register(NetworkState.PLAY, 0x1E, EntityAction::new);
		registry.register(NetworkState.PLAY, 0x1F, SteerVehicle::new);
		registry.register(NetworkState.PLAY, 0x20, SyncPong::new);
		registry.register(NetworkState.PLAY, 0x21, RecipeBookState::new);
		registry.register(NetworkState.PLAY, 0x22, RecipeBookRecipe::new);
		registry.register(NetworkState.PLAY, 0x23, NameItem::new);
		registry.register(NetworkState.PLAY, 0x24, ResourcePackStatus::new);
		registry.register(NetworkState.PLAY, 0x25, AdvancementTab::new);
		registry.register(NetworkState.PLAY, 0x26, SelectTrade::new);
		registry.register(NetworkState.PLAY, 0x27, SetBeaconEffect::new);
		registry.register(NetworkState.PLAY, 0x28, HeldSlot::new);
		registry.register(NetworkState.PLAY, 0x29, UpdateCommandBlock::new);
		registry.register(NetworkState.PLAY, 0x2A, UpdateCommandMinecart::new);
		registry.register(NetworkState.PLAY, 0x2B, CreativeSetSlot::new);
		registry.register(NetworkState.PLAY, 0x2C, JigsawUpdate::new);
		registry.register(NetworkState.PLAY, 0x2D, UpdateStructureBlock::new);
		registry.register(NetworkState.PLAY, 0x2E, UpdateSign::new);
		registry.register(NetworkState.PLAY, 0x2F, Animation::new);
		registry.register(NetworkState.PLAY, 0x30, Spectate::new);
		registry.register(NetworkState.PLAY, 0x31, BlockPlace::new);
		registry.register(NetworkState.PLAY, 0x32, UseItem::new);
	}

}
